### ISSUE TITLE
Module to unpack event logs based on ABI 

### ISSUE THREAD

**Issue by robcxyz** [sudoblockio/icon-tracker-frontend#224]
Need to build module that unpacks the event log based on the ABI. For instance:

https://tracker.icon.community/transaction/0xabaa9a86a955750733b877b2bd034ef295c8d26d84e9efc2dd2d235d59d5982f#events

Raw Event Log: (event logs trimmed -> Original has 25 event logs 
```
        "blockHeight": "0x3c9345a",
        "cumulativeStepUsed": "0x3c0c411",
        "eventLogs": [
            {
                "scoreAddress": "cxa0af3165c08318e988cb30993b3048335b94af6c",
                "indexed": [
                    "Add(int,Address,int,int,int)",
                    "0x30",
                    "cxed0f02a1a61b483bd366021d68af8469414b7be8",
                    "0x4084154109e3519"
                ],
                "data": [
                    "0xefcee47256c0000",
                    "0x11cca8ded80a621"
                ]
            }
        ],
        "status": "0x1",
        "stepPrice": "0x2e90edd00",
        "stepUsed": "0x3c0c411",
        "to": "cx2aa9b28a657e3121b75d3d4fe65e569398645d56",
        "txHash": "0xabaa9a86a955750733b877b2bd034ef295c8d26d84e9efc2dd2d235d59d5982f",
```

Can be decoded with this ABI:

ABI: 
```
{
		"inputs": [
			{
				"indexed": "0x1",
				"name": "_id",
				"type": "int"
			},
			{
				"indexed": "0x1",
				"name": "_owner",
				"type": "Address"
			},
			{
				"indexed": "0x1",
				"name": "_value",
				"type": "int"
			},
			{
				"name": "_base",
				"type": "int"
			},
			{
				"name": "_quote",
				"type": "int"
			}
		],
		"name": "Add",
		"type": "eventlog"
	},
```

**Unprocessed Event log**
```yaml
origin: cxa0af3165c08318e988cb30993b3048335b94af6c
_id: 0x4
_owner: hx157efafb1abad56a2224e1a743c6fea24c32331f
_value: 0x1cb81fef756c4bcb0e
_base: 0x2a6d50eb5e2ac3dbd1
_quote: 0x1544b515feabaa5c7a
```

**Processed Event log**
```yaml
origin: cxa0af3165c08318e988cb30993b3048335b94af6c
_id: 4
_owner: hx157efafb1abad56a2224e1a743c6fea24c32331f
_value: 529776420378731334414
_base: 782640305633749097425
_quote: 392332513096810257530
```

We need to have both the raw and processed event log. Be aware of all the types that can result from an event log -> https://www.notion.so/sudoblock/Read-Write-Methods-and-Types-0a8d0d413ae648538125fc9e5a473678

## Tests

- Function x2 -> One for unprocessed and one for processed (they should wrap each other)
  - Inputs: Result of getTransactionResult and the ABI 
  - Output: List of maps per above format - unproxessed without converting ints / processed converting ints 
- Read in some json fixtures for both -> Balanced Dex -> https://tracker.icon.community/contract/cxa0af3165c08318e988cb30993b3048335b94af6c
- Call the function and assert some of the fields as being valid
